name: productos_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
version: 11.5.0

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  flutter_secure_storage: ^9.0.0
  http: ^0.13.3
  image_picker: ^0.8.7+3
  provider: ^5.0.0
  get_storage: ^2.0.3
  shared_preferences: ^2.1.1
  intl: ^0.18.0
  pie_chart: ^5.3.2
  cached_network_image: ^3.3.1
  flutter_blurhash: ^0.8.2
  connectivity_plus: ^4.0.1
  table_calendar: ^3.0.8
  permission_handler: ^11.3.1
  path_provider: ^2.0.15
  url_launcher: ^6.1.10
  font_awesome_flutter: ^10.5.0
  flutter_downloader: ^1.11.0
  flutter_cache_manager: ^3.3.1
  webview_flutter: ^4.2.1
  location: ^5.0.2
  geolocator: ^11.0.0
  flutter_email_sender: ^6.0.3
  flutter_local_notifications: ^17.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/